### ISSUE TITLE
Update does not start

### ISSUE THREAD

**Issue by rootzoll** [cstenglein/raspiblitz-web#332] opened 2022-06-05 23:44 UTC
When I was testing the "update" scenario with a real RaspiBlitz it started correct by detecting the setupPhase `update` and asking if I wanna update:
![Bildschirmfoto 2022-06-06 um 01 38 05](https://user-images.githubusercontent.com/2472225/172075412-c526c4d2-ad55-4376-a5a6-787933f4f86e.png)

Then asks to enter a new passwordA, but then asks "If I want to start recovery" and when I press "start recovery" button there is no HTTPs request - it just jumps back to beginning of the dialog like above - basically going in circles.
![Bildschirmfoto 2022-06-06 um 01 38 25](https://user-images.githubusercontent.com/2472225/172075456-8031c8f0-cb57-457a-957e-a93a034ab0a7.png)
s

**Comment by cstenglein** [comment] 2022-06-06 04:28
Can't reproduce (with mock-backend)

=> Can you show me later?

**Comment by cstenglein** [comment] 2022-06-06 12:12
Fixed with https://github.com/cstenglein/raspiblitz-web/pull/336

**Closed** 2022-06-06 12:12 UTC
Labels: App:Setup, prio:high, Test on Blitz
